# Generated by Django 4.0.10 on 2024-07-27 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0002_catechumene_animateur_catechumene_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catechumene',
            name='categorie',
            field=models.CharField(choices=[('enfant', 'Enfant'), ('jeune', 'Jeune'), ('adulte', 'Adulte')], max_length=20),
        ),
        migrations.AlterField(
            model_name='catechumene',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='catechumene',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='catechumene',
            name='matricule',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='catechumene',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catechumene', to=settings.AUTH_USER_MODEL),
        ),
    ]
