# Generated by Django 4.0.10 on 2024-07-27 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_catechumene_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animateur',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animateur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animateur',
            name='nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animateur_photos/'),
        ),
        migrations.AddField(
            model_name='animateur',
            name='prenom',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
