# Generated by Django 4.0.10 on 2024-08-05 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_parent_contact_parent_date_creation_parent_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
